# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

include ${LAYERDIR}/include/openamp.inc

# Support for remoteproc ("0" for no support and "1" for support)
ENABLE_REMOTEPROC ?= "1"

# Remote core selection ("0" for R52 and "1" for A55)
RPMSG_REMOTE_CORE ?= "0"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"
	
BBFILE_COLLECTIONS += "rz-multi-os"
BBFILE_PATTERN_rz-multi-os := "^${LAYERDIR}/"

LAYERDEPENDS_rz-multi-os = "rzt2h"
LAYERSERIES_COMPAT_rz-multi-os = "dunfell"
